 /*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

 repositories {
     mavenCentral()
     google()
     gradlePluginPortal()
 }


dependencies {
    // Dependência do MySQL Connector
    implementation("com.mysql:mysql-connector-j:8.3.0")

    // Dependência do Kotlin Standard Library
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.22")

    // Dependência do JUnit Jupiter para testes
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.0")

    // Dependência do Lombok para reduzir código boilerplate
    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    // Dependência do Liquibase para migração de banco de dados
    implementation("org.liquibase:liquibase-core:4.25.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

 application {
     mainClass = "br.com.dio.Main"
 }
